# Generated by Django 4.1.1 on 2022-09-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discogapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discog",
            name="genres",
            field=models.ManyToManyField(
                related_name="discogs",
                through="discogapi.DiscogGenre",
                to="discogapi.genre",
            ),
        ),
    ]
