# Generated by Django 4.1.1 on 2022-09-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("discogapi", "0002_discog_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discuser",
            name="full_name",
        ),
        migrations.AddField(
            model_name="discog",
            name="user_discog",
            field=models.ManyToManyField(
                related_name="discogs",
                through="discogapi.UserDiscog",
                to="discogapi.discuser",
            ),
        ),
        migrations.AlterField(
            model_name="userdiscog",
            name="disc_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="discogapi.discuser"
            ),
        ),
    ]
